name: Deploy AWS Cognito and Lambda with Terraform

on:
  push:
    branches:
      #- main - Quando estiver OK, deixar apenas main 
      - develop 
  pull_request:
    branches:
      #- main - Quando estiver OK, deixar apenas main 
      - develop

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.0

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y zip

    - name: Zip Lambda Function
      run: zip -r lambda_registry_client.zip src/lambda_function.js

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      run: terraform apply -auto-approve

    - name: Upload Lambda Deployment Package
      uses: actions/upload-artifact@v3
      with:
        name: lambda_registry_client.zip
        path: lambda_registry_client.zip
